name: Run tests

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on:
      group: Default
      labels: cluster-runner
    steps:
      - uses: actions/checkout@v4

      # Necessary for installing nix (alternative: create a custom gh runner image)
      - name: Install xz
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils

      - name: Install nix
        uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1

      - name: Run tests
        # Some tests fail on the self-hosted runner, but because they're not relevant to our work, we disable them.
        run: |
          nix develop --command go test -short -count=1 -skip "UPNP|PathExpansion|TestUDPv4_findnode" ./...
